global:
  runner: razorci/base
tasks:
  build-image:
    steps:
      image: iotplatform6.jfrog.io/go-api/hello-world
      push: true
      tags: ["latest"]
      dockerfile: Dockerfile
      context: .
      url: iotplatform6.jfrog.io
      Username: iotplatform6@gmail.com
      Password: Qazwsx123@
