tasks:
  build-image:
    type: build
    image: iotplatform6.jfrog.io/artifactory/dockerhub/golang
    tags: ["latest"]
    dockerfile: Dockerfile
    context: .
    runner: golang

    # - docker-push:
    #     image: dockerhub/goapi
    #     tags: ["latest"]

# tasks:
#   build-image:
#     type: build
#     image: saurabh3460/go-api-test
#     push: true
#     tags: ["latest"]
#     dockerfile: Dockerfile
#     context: .
#     runner: golang