global:
  runner: razorci/base
tasks:
  build-image:
    steps:
      - docker-build:
        image: dockerhub/goapi
        # push: true
        tags: ["latest"]
        dockerfile: Dockerfile
        context: .
      - docker-push:
          image: dockerhub/goapi
          tags: ["latest"]
