global:
  runner: razorci/base
tasks:
  build-image:
    steps:
      - docker-build:
        image: go-api
        push: true
        tags: ["latest"]
        dockerfile: Dockerfile
        context: .
      - docker-push:
          image: iotplatform6.jfrog.io/go-api/hello-world
          tags: ["latest"]
          url: iotplatform6.jfrog.io
          Username: iotplatform6@gmail.com
          Password: Qazwsx123@
